from forms.loginform import LoginForm
from forms.registerform import RegisterForm
from forms.userform import UserForm
from forms.balanceform import BalanceForm
from forms.adminkeyform import AdminKeyForm
from forms.productform import ProductForm
from forms.reviewform import ReviewForm
from forms.usersearchform import UserSearchForm
from forms.productsearchform import ProductSearchForm
from forms.ordersubmitform import OrderSubmitForm
